# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.8.1
_src_path: gh:algorandfoundation/algokit-python-template
author_email: ramanadhamjayaveer@gmail.com
author_name: jayaveerR
contract_name: student
deployment_language: python
preset_name: starter
project_name: backend-contracts

