# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.1.8
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: ramanadhamjayaveer@gmail.com
author_name: jayaveerR
contract_name: student
deployment_language: python
preset_name: starter
project_name: backend

